# PARAMETERS RELATED TO THE AUDIO PROCESSING 
# AND FOR THE CONVERSION FROM AUDIO TO MEL_SPECTROGRAM

SAMPLE_RATE = 16000
N_FFT = 1024
HOP_LENGTH = 320
WIN_LENGTH = 640 # (20 ms)
N_MEL_CHANNELS = 128
MEL_FMIN = 0.0
MEL_FMAX = int(SAMPLE_RATE // 2)
CLIP_VALUE_MIN = 1e-5
CLIP_VALUE_MAX = 1e8